AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for running Kittens Carousel Static Website on EC2. 
  Kittens Carousel Static Website will be deployed on Amazon Linux 2  EC2 Instance with 
  custom security group which allows http connections on port 80 and ssh port 22 from anywhere. 
  Kittens Carousel Static Website is downloaded from my Public Github repository,
  then deployed on Apache Web Server.

Parameters:

  ImageId: 
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

  Subnets:
    Description: select your subnet
    Type: AWS::EC2::Subnet::Id

  MyKey:
    Description: Select your key-pair
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Select your instance type. Default is t2.micro.

  VPC:
    Description: select your VPC
    Type: AWS::EC2::VPC::Id

Resources:

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref MyKey
      SecurityGroupIds:
        - !Ref MySecGrp
      SubnetId: !Ref Subnets
      Tags:
        - Key: Name
          Value: !Sub "Web server of {AWS::StackName} stack"
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install httpd -y
        FOLDER="https://raw.githubusercontent.com/balaban1432/my-projects/main/aws/projects/Project-101-kittens-carousel-static-website-ec2/static-web"
        cd /var/www/html
        wget $FOLDER/index.html
        wget $FOLDER/cat0.jpg
        wget $FOLDER/cat1.jpg
        wget $FOLDER/cat2.jpg
        wget $FOLDER/cat3.png
        systemctl start httpd
        systemctl enable httpd

  MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh and http. # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22 
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80 
          ToPort: 80
          CidrIp: 0.0.0.0/0 
      VpcId: !Ref VPC
      Tags: 
        - Key: Name
          Value: !Sub "Webserver security group of ${AWS::StackName} Stack"

Outputs:
  
  WebsiteURL:
    Description: Kittens Carousel Application URL
    Value: !Join
      - ''
      - - 'http://'
        - !GetAtt WebServer.PublicDnsName
        