apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
  namespace: default
spec:
  storageClassName: manuel
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi