apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - name: db
    protocol: TCP
    port: 3306
    targetPort: 3306