apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultserver-deployment
  namespace: default
  labels:
    app: result-server
spec:
  selector:
    matchLabels:
      app: result-server
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: result-server
        tier: frontend
    spec:
      containers:
      - name: resultserver
        image: balaban/result-server
        env:
        - name: MYSQL_DATABASE_HOST
          value: mysql-service
        - name: MYSQL_PASSWORD
          value: RamazanBALABAN_1
        - name: MYSQL_DATABASE
          value: phonebook
        - name: MYSQL_USER
          value: admin
        ports:
        - containerPort: 80