apiVersion: v1
kind: Service
metadata:
  name: resultserver-service
spec:
  selector:
    app: resultserver
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002