apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  MYSQL_DATABASE: {{ .Values.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.MYSQL_USER }}
  MYSQL_DATABASE_HOST: {{ .Values.MYSQL_DATABASE_HOST }}