apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: default
spec:
  selector:
    app: web-server
    tier: backend
  type: NodePort
  ports:
  - name: webserver
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001