apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: default
  labels:
    app: web-server
spec:
  selector:
    matchLabels:
      app: web-server
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: web-server
        tier: backend
    spec:
      containers:
      - name: webserver
        image: balaban/web-server
        envFrom:
          - secretRef:
              name: appsecret
          - configMapRef:
              name: server-config
        ports:
        - containerPort: 80