services:
  
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=R123456b
      - MYSQL_DATABASE=bookstore_db
      - MYSQL_USER=clarusway
      - MYSQL_PASSWORD=Clarusway_1
    networks:
      - balabannet
    volumes:
      - mysql-data:/var/lib/mysql      
    restart: always
   
  server:
    build: .
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - balabannet
    restart: always

networks:
  balabannet:
    driver: bridge

volumes:
  mysql-data:   